library(Rcpp)
library(RcppArmadillo)
library(mvtnorm)
library(Matrix)
library(MCMCpack)
library(VGAM)
library(stringr)
library(plyr)
library(pryr)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(lme4)
detach("package:plyr", unload=TRUE)

